name: first workflow
on:
    workflow_dispatch:
        inputs:
            versionName:
                required: true
                description: "version name for github workflow"
    # repository_dispatch:
    #     types: [test]
    # push:
    #     branches:
    #         - "main"
    # pull_request:
    #     branches:
    #         - "freature"
    #     types: [opened, closed]
  
jobs:
    First-workflow-job:
        name: first job
        runs-on: ubuntu-latest
        steps:
            - name: before checkout action 
              run: ls
              shell: bash
            - name: checkout steps
              uses: actions/checkout@v3

            - name: after checkout steps 
              run: ls
              shell: bash
