name: first-worlflow
on:
    repository_dispatch:
      types: [test]
    push:
        branches:
            - "main"
    pull_request:
      branches:
        - "feature"
      types: [opened, closed]
jobs:
    first-workflow-job:
        name: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Before Checkout Action
              run: ls #echo "first workflow"
              shell: bash
            - name: checkout step
              uses: actions/checkout@v3
            - name: After Checkout Action
              run: ls
              shell: bash


