name: Repository Despatch
on:
    repository_dispatch:
        types: [test]
    push:
        branches:
            - "main"
        types: [test1]
    push:
        branches:
            - "main"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - run: ls
            shell: bash